{
 "title": "ClickHouse New",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "satvis",
    "query": "select distinct(sat) from rawdata.satxyz2 where time between $from and $to"
   },
   {
    "name": "satgraph",
    "query": "select distinct(sat) from rawdata.satxyz2 where time between $from and $to"
   },
   {
    "name": "freq",
    "query": "select distinct(freq) from rawdata.range where sat='$satgraph' and time between $from and $to"
   },
   {
    "name": "sigcomb",
    "query": "select distinct(sigcomb) from computed.NT where sat='$satgraph' and time between $from and $to"
   },
   {
    "name": "TEC_secondaryfreq",
    "query": "select distinct(secondaryfreq) from rawdata.ismrawtec where sat='$satgraph' and time between $from and $to"
   }
  ]
 },
 "panels": [
  { "title": "Данные", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Псевдодальности",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "lengthm", "label": "PSR" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'PSR %sat %freq',\n    avg(psr) psr)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    AND freq IN ($freq)",
     "rawQuery": "SELECT t, groupArray((concat('PSR ', sat, ' ', freq), psr)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, freq, avg(psr) psr FROM rawdata.range WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = 'GPS30'     AND freq IN ('L1CA') GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "range"
    }
   ]
  },
  {
   "title": "ПЭС",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "TECU" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'TEC %sat %sigcomb',\n    avg(nt) nt)\nFROM $table final\nWHERE\n    sat = '$satgraph'\n    and sigcomb in ($sigcomb)",
     "rawQuery": "SELECT t, groupArray((concat('TEC ', sat, ' ', sigcomb), nt)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(nt) nt FROM computed.NT final WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = 'GPS30'     and sigcomb in ('L1CA+L2C','L1CA+L5Q') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NT"
    }
   ]
  },
  {
   "title": "Псевдофазы",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "ADR" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'ADR %sat %freq',\n    avg(adr) adr)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    AND freq IN ($freq)",
     "rawQuery": "SELECT t, groupArray((concat('ADR ', sat, ' ', freq), adr)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, freq, avg(adr) adr FROM rawdata.range WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = 'GPS30'     AND freq IN ('L1CA') GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "range"
    }
   ]
  },
  {
   "title": "ПЭС",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "TECU" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Сырой TEC %sat L1CA+%secondaryfreq',\n    avg(tec) tec)\nFROM $table\nWHERE\n    secondaryfreq IN ($TEC_secondaryfreq)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Average TEC ', sat, '  ', sigcomb), avgNT)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(avgNT) avgNT FROM computed.NTDerivatives WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = 'GPS30'     and sigcomb in ('L1CA+L2C','L1CA+L5Q') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ismrawtec"
    }
   ]
  },
  {
   "title": "C/No",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Elevation %sat',\n    avg(elevation) elevation)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Elevation ', sat), elevation)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, avg(elevation) elevation FROM rawdata.satxyz2 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "satxyz2"
    },
    {
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'C/No %sat %freq',\n    avg(cno) cno)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    AND freq IN ($freq)",
     "rawQuery": "SELECT t, groupArray((concat('C/No ', sat, ' ', freq), cno)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, freq, avg(cno) cno FROM rawdata.range WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = '$sat'     AND freq IN ('L1CA') GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "range"
    }
   ]
  },
  {
   "title": "Среднее ПЭС",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "TECU" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Average TEC %sat  %sigcomb',\n    avg(avgNT) avgNT)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    and sigcomb in ($sigcomb)    ",
     "rawQuery": "SELECT t, groupArray((concat('TEC deviation ', sat, ' ', sigcomb), delNT)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(delNT) delNT FROM computed.NTDerivatives WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = 'GPS30'     and sigcomb in ('L1CA+L2C','L1CA+L5Q') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NTDerivatives"
    }
   ]
  },
  {
   "title": "F",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "hertz", "label": "F" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'f1 %sat %sigcomb',\n    avg(f1) f1\n    )\nFROM $table final\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('f1 ', sat, ' ', sigcomb), f1)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(f1) f1 FROM computed.NT final WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = 'GPS30'     and sigcomb in ('L1CA+L2C','L1CA+L5Q') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NT"
    },
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'f2 %sat %sigcomb',\n    avg(f2) f2\n    )\nFROM $table final\nWHERE\n    sat = '$sat'",
     "rawQuery": "SELECT t, groupArray((concat('f2 ', sat, ' ', sigcomb), f2)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(f2) f2 FROM computed.NT final WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      sat = '$sat'     and sigcomb in ('L1CA+L2C','L1CA+L5Q') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NT"
    }
   ]
  },
  {
   "title": "СКО флуктуаций ПЭС",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "TECU" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'TEC deviation %sat %sigcomb',\n    avg(delNT) delNT)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    and sigcomb in ($sigcomb)",
     "rawQuery": "SELECT t, groupArray((concat('TEC deviation ', sat, ' ', sigcomb), delNT)) as groupArr FROM ( SELECT intDiv(time, 2000) * 2000 as t, sat, sigcomb, avg(delNT) delNT FROM computed.NTDerivatives WHERE d >= toDate(1641383524120/1000) AND time >= 1641383524120 AND      sat = 'GPS30'     and sigcomb in ('L1CA+L2C','L1CA+L5Q') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NTDerivatives"
    }
   ]
  },
  { "title": "Computed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "СКО флуктуаций фазы (L1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "radian", "label": "Radians" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'SigmaPhi %sat  %sigcomb',\n    avg(sigPhi) sigPhi)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('SigmaPhi ', sat, '  ', sigcomb), sigPhi)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(sigPhi) sigPhi FROM computed.xz1 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xz1"
    }
   ]
  },
  {
   "title": "Параметр Райса (L1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Gamma %sat %sigcomb',\n    avg(gamma) gamma)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Gamma ', sat, ' ', sigcomb), gamma)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(gamma) gamma FROM computed.xz1 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xz1"
    }
   ]
  },
  {
   "title": "Интервал частотной корреляции (L1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Fc %sat %sigcomb',\n    avg(Fc) Fc)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Fc ', sat, ' ', sigcomb), Fc)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(Fc) Fc FROM computed.xz1 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xz1"
    }
   ]
  },
  {
   "title": "Интервал пространственной корреляции (L1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Fc %sat %sigcomb',\n    avg(Pc) Pc)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Fc ', sat, ' ', sigcomb), Pc)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(Pc) Pc FROM computed.xz1 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xz1"
    }
   ]
  },
  { "title": "Карты", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Подионосферная точка",
   "type": "satmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'ПИТ sat=%sat',\n    any(ionpoint) g)\nFROM $table\nWHERE sat IN ($satvis)",
     "rawQuery": "SELECT t, groupArray((concat('ПИТ sat=', sat), g)) as groupArr FROM ( SELECT intDiv(time, 1000) * 1000 as t, sat, any(ionpoint) g FROM rawdata.satxyz2 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat IN ('GLONASS1','GPS2','GPS4','GPS6','GLONASS7','GPS7','GLONASS8','GLONASS9','GPS9','GLONASS11','GPS16','GPS30') GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "satxyz2"
    }
   ]
  },
  {
   "title": "Подспутниковая точка",
   "type": "satmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'ПИТ sat=%sat',\n    any(geopoint) g)\nFROM $table\nWHERE sat IN ($satvis)",
     "rawQuery": "SELECT t, groupArray((concat('ПИТ sat=', sat), g)) as groupArr FROM ( SELECT intDiv(time, 1000) * 1000 as t, sat, any(geopoint) g FROM rawdata.satxyz2 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat IN ('GLONASS1','GPS2','GPS4','GPS6','GLONASS7','GPS7','GLONASS8','GLONASS9','GPS9','GLONASS11','GPS16','GPS30') GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "satxyz2"
    }
   ]
  },
  {
   "title": "Подионосферные точки",
   "type": "satmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "aggregator": "sum",
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'sat=%sat',\n    any(ionpoint) g)\nFROM $table\nWHERE sat IN ($satvis)",
     "rawQuery": "SELECT t, groupArray((concat('sat=', sat), g)) as groupArr FROM ( SELECT intDiv(time, 1000) * 1000 as t, sat, any(ionpoint) g FROM rawdata.satxyz2 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat IN ('GLONASS1','GPS2','GPS4','GPS6','GLONASS7','GPS7','GLONASS8','GLONASS9','GPS9','GLONASS11','GPS16','GPS30') GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "satxyz2"
    }
   ]
  },
  {
   "title": "АКФ (L1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Tc %sat %sigcomb',\n    avg(Tc) Tc)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Tc ', sat, ' ', sigcomb), Tc)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, sigcomb, avg(Tc) Tc FROM computed.Tc WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "Tc"
    }
   ]
  },
  { "title": "Видимость спутников", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "B",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'B %sat',\n    avg(s4 / 100) s4)\nFROM $table\nWHERE sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('B ', sat), s4)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, avg(s4 / 100) s4 FROM computed.s4 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND  sat = 'GPS30' GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "s4"
    }
   ]
  },
  {
   "title": "S4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'S4 %sat %freq',\n    avg(s4) s4)\nFROM $table\nWHERE\n    freq IN ($freq)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('S4 ', sat, ' ', freq), s4)) as groupArr FROM ( SELECT intDiv(time, 500) * 500 as t, sat, freq, avg(s4) s4 FROM computed.s4 WHERE d BETWEEN toDate(1595878988378/1000) AND toDate(1595879279537/1000) AND time BETWEEN 1595878988378 AND 1595879279537 AND      freq IN ('L1CA')     AND sat = 'GPS30' GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "s4"
    }
   ]
  },
  {
   "title": "S4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "database": "rawdata",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Сырое S4 %sat %freq',\n    avg(totals4) totals4)\nFROM $table\nWHERE\n    freq IN ($freq)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Сырое S4 ', sat, ' ', freq), totals4)) as groupArr FROM ( SELECT intDiv(time, 2000) * 2000 as t, sat, freq, avg(totals4) totals4 FROM rawdata.ismredobs WHERE d >= toDate(1641383524120/1000) AND time >= 1641383524120 AND      freq IN ('L1CA','L2C','L2P_codeless')     AND sat = 'GPS30' GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ismredobs"
    }
   ]
  }
 ]
}