{
 "title": "Суточный мониторинг",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "satvis",
    "query": "select distinct(sat) from computed.satxyz2 where time between $__from and $__to"
   },
   {
    "name": "satgraph",
    "query": "select distinct(sat) from computed.satxyz2 where time between $__from and $__to"
   },
   {
    "name": "freq",
    "query": "select distinct(freq) from computed.range where sat='$satgraph' and time between $__from and $__to"
   },
   {
    "name": "sigcomb",
    "query": "select distinct(sigcomb) from computed.NT where sat='$satgraph' and time between $__from and $__to"
   },
   {
    "name": "TEC_secondaryfreq",
    "query": "select distinct(secondaryfreq) from computed.ismrawtec where sat='$satgraph' and time between $__from and $__to"
   }
  ]
 },
 "panels": [
  {
   "title": "Данные",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ПЭС",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'TEC %sat %sigcomb',\n    avg(nt) nt)\nFROM $table final\nWHERE\n    sat = '$satgraph'\n    and sigcomb in ($sigcomb)",
     "rawQuery": "SELECT t, groupArray((concat('TEC ', sat, ' ', sigcomb), nt)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, sigcomb, avg(nt) nt FROM computed.NT final WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      sat = 'GLONASS1'     and sigcomb in ('L1CA+L2CA','L1CA+L2P') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NT"
    }
   ]
  },
  {
   "title": "C/No",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Elevation %sat',\n    avg(elevation) elevation)\nFROM $table\nWHERE\n    sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Elevation ', sat), elevation)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, avg(elevation) elevation FROM computed.satxyz2 WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND  sat = 'GLONASS1' GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "satxyz2"
    },
    {
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'C/No %sat %freq',\n    avg(cno) cno)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    AND freq IN ($freq)",
     "rawQuery": "SELECT t, groupArray((concat('C/No ', sat, ' ', freq), cno)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, freq, avg(cno) cno FROM computed.range WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      sat = 'GLONASS1'     AND freq IN ('L1CA') GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "range"
    }
   ]
  },
  {
   "title": "ПЭС ОЕМ6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Сырой TEC %sat L1CA+%secondaryfreq',\n    avg(tec) tec)\nFROM $table\nWHERE\n    secondaryfreq IN ($TEC_secondaryfreq)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Сырой TEC ', sat, ' L1CA+', secondaryfreq), tec)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, secondaryfreq, avg(tec) tec FROM computed.ismrawtec WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      secondaryfreq IN ('L2CA','L2P')     AND sat = 'GLONASS1' GROUP BY t, sat, secondaryfreq  ORDER BY t, sat, secondaryfreq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ismrawtec"
    }
   ]
  },
  {
   "title": "Среднее ПЭС",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Average TEC %sat  %sigcomb',\n    avg(avgNT) avgNT)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    and sigcomb in ($sigcomb)    ",
     "rawQuery": "SELECT t, groupArray((concat('Average TEC ', sat, '  ', sigcomb), avgNT)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, sigcomb, avg(avgNT) avgNT FROM computed.NTDerivatives WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      sat = 'GLONASS1'     and sigcomb in ('L1CA+L2CA','L1CA+L2P') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "NTDerivatives"
    }
   ]
  },
  {
   "title": "Подионосферная точка",
   "type": "satmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'ПИТ sat=%sat',\n    any(ionpoint) g)\nFROM $table\nWHERE sat IN ($satvis)",
     "rawQuery": "SELECT t, groupArray((concat('ПИТ sat=', sat), g)) as groupArr FROM ( SELECT intDiv(time, 1000) * 1000 as t, sat, any(ionpoint) g FROM computed.satxyz2 WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND  sat IN ('GLONASS1') GROUP BY t, sat  ORDER BY t, sat) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "satxyz2"
    }
   ]
  },
  {
   "title": "СКО флуктуаций ПЭС",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'TEC deviation STD %sat %sigcomb',\n    avg(sigNT) sigNT)\nFROM $table\nWHERE\n    sat = '$satgraph'\n    and sigcomb in ($sigcomb)",
     "rawQuery": "SELECT t, groupArray((concat('TEC deviation STD ', sat, ' ', sigcomb), sigNT)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, sigcomb, avg(sigNT) sigNT FROM computed.xz1 WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      sat = 'GLONASS1'     and sigcomb in ('L1CA+L2CA','L1CA+L2P') GROUP BY t, sat, sigcomb  ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "xz1"
    }
   ]
  },
  {
   "title": "Мощностной S4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'S4 %sat %freq',\n    avg(s4) s4)\nFROM $table\nWHERE\n    freq IN ($freq)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('S4 ', sat, ' ', freq), s4)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, freq, avg(s4) s4 FROM computed.s4 WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      freq IN ('L1CA')     AND sat = 'GLONASS1' GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "s4pwr"
    }
   ]
  },
  {
   "title": "S4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'S4 %sat %sigcomb',\n    avg(s4) s4)\nFROM $table\nWHERE\n    sigcomb IN ($sigcomb)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('S4 ', sat, ' ', sigcomb), s4)) AS groupArr FROM ( SELECT (intDiv(time, (5 * 1000)) * (5 * 1000)) AS t, sat, sigcomb, avg(s4) s4 FROM computed.s4\nWHERE time >= toUInt64(1664038327 * 1000) AND time <= toUInt64(1664049127 * 1000) AND\n    sigcomb IN ('L1CA+L2CA','L1CA+L2P')\n    AND sat = 'GLONASS1' GROUP BY t, sat, sigcomb ORDER BY t, sat, sigcomb) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "s4"
    }
   ]
  },
  {
   "title": "S4 ОЕМ6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "database": "computed",
     "dateColDataType": "d",
     "dateTimeColDataType": "time",
     "dateTimeType": "TIMESTAMPMS",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(\n    'Сырое S4 %sat %freq',\n    avg(totals4) totals4)\nFROM $table\nWHERE\n    freq IN ($freq)\n    AND sat = '$satgraph'",
     "rawQuery": "SELECT t, groupArray((concat('Сырое S4 ', sat, ' ', freq), totals4)) as groupArr FROM ( SELECT intDiv(time, 15000) * 15000 as t, sat, freq, avg(totals4) totals4 FROM computed.ismredobs WHERE d >= toDate(1656762638574/1000) AND time >= 1656762638574 AND      freq IN ('L1CA')     AND sat = 'GLONASS1' GROUP BY t, sat, freq  ORDER BY t, sat, freq) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "ismredobs"
    }
   ]
  }
 ]
}